[package]
name = "solo-ttrpg-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
rand = "~0.8.5"
thiserror = "1.0.32"

[dev-dependencies]
quickcheck = "1.0"
quickcheck_macros = "1.0"
